---
# tasks file for extend-disk

- name: Read device information (always use unit when probing)
  parted: 
    device: "{{ disk }}"
    unit: MiB
  register: disk_info

- name: Print return information from the previous task
  debug:
    var: disk_info
    verbosity: 2

- name: Extend the existing partition to fill all available space
  parted:
    device: "{{ disk }}"
    number: "{{ disk_info.partitions | length }}"
    part_end: "100%"
    resize: true
    state: present