---
# tasks file for extend-disk

- name: Read device information (always use unit when probing)
  community.general.parted: 
    device: "{{ disk }}"
    unit: MiB
  register: disk_info

- name: Print return information from the previous task
  debug:
    var: disk_info
    verbosity: 2

- name: Extend the existing partition to fill all available space
  community.general.parted:
    device: "{{ disk }}"
    number: "{{ disk_info.partitions | length }}"
    label: gpt
    unit: MiB
    part_end: "100%"
    state: present
    resize: true

# - name: Add new partition to {{ disk }}
#   parted:
#     device: "{{ disk }}"
#     number: "{{ disk_info.partitions | length + 1 }}"
#     part_type: primary
#     flags: [ lvm ]
#     state: present
#     part_end: "100%"
#     part_start: "{{ (disk_info.partitions | last).end + 1}}MiB" 

# - name: Add device to exising volume group {{ volume_group }}
#   lvg:
#     vg: "{{ volume_group }}"
#     pvs: "{{ disk }}{{ disk_info.partitions | length }},{{ disk }}{{ disk_info.partitions | length + 1 }}"