---
# tasks file for extend-disk

- name: Read device information (always use unit when probing)
  community.general.parted: 
    device: "{{ disk }}"
    unit: MiB
  register: disk_info

- name: Print return information from the previous task
  debug:
    var: disk_info
    verbosity: 2

- name: Extend the existing partition to fill all available space
  community.general.parted:
    device: "{{ disk }}"
    number: "{{ disk_info.partitions | length }}"
    label: gpt
    unit: MiB
    part_end: "100%"
    state: present
    resize: true

- name: Extend the LVM to the new space on {{ disk }}
  community.general.lvg:
    vg: "{{ volume_group }}"
    pvs: "{{ disk }}{{ disk_info.partitions | length }}"
    pvresize: true

- name: Extend the logical volume to take all remaining space and resize the underlying filesystem
  community.general.lvol:
    vg: "{{ volume_group }}"
    lv: "{{ logical_volume }}"
    size: +100%FREE
    resizefs: true